# frozen_string_literal: true

source "https://rubygems.org"

# Pull in the engine’s dependencies
eval_gemfile "../../Gemfile"

# Dummy‑only gems live below this line
gem "mission_control-jobs", "~> 1.1"
